// Pages des Paramètres Windows proposées par la recherche du lanceur.
// `page` correspond à la liste fermée de la commande Rust open_settings.
export const SETTINGS_PAGES = [
  ["wifi", "Wi-Fi", "reseau internet sans fil wlan"],
  ["network", "Réseau et Internet", "ethernet connexion ip proxy"],
  ["vpn", "VPN", "reseau prive"],
  ["bluetooth", "Bluetooth et appareils", "casque souris clavier appairage"],
  ["display", "Écran", "resolution luminosite hdr ecran moniteur echelle"],
  ["nightlight", "Éclairage nocturne", "lumiere bleue nuit"],
  ["sound", "Son", "audio volume haut-parleur micro microphone"],
  ["notifications", "Notifications", "alertes ne pas deranger"],
  ["power", "Alimentation et mise en veille", "veille energie batterie"],
  ["battery", "Économiseur de batterie", "batterie autonomie"],
  ["storage", "Stockage", "disque espace nettoyage"],
  ["printers", "Imprimantes et scanners", "imprimer scanner"],
  ["mouse", "Souris et pavé tactile", "curseur touchpad defilement"],
  ["keyboard", "Saisie et clavier", "clavier correction orthographe"],
  ["personalization", "Personnalisation", "theme apparence"],
  ["background", "Arrière-plan", "fond d'ecran image"],
  ["colors", "Couleurs", "accent sombre clair"],
  ["lockscreen", "Écran de verrouillage", "verrouillage"],
  ["apps", "Applications installées", "desinstaller programmes logiciels"],
  ["defaultapps", "Applications par défaut", "navigateur par defaut ouvrir avec"],
  ["startup", "Applications au démarrage", "demarrage lancement"],
  ["accounts", "Comptes", "compte utilisateur profil"],
  ["signin", "Options de connexion", "mot de passe code pin windows hello"],
  ["datetime", "Date et heure", "horloge fuseau heure"],
  ["language", "Langue et région", "langue region francais"],
  ["privacy", "Confidentialité et sécurité", "vie privee autorisations localisation camera"],
  ["update", "Windows Update", "mise a jour mises a jour"],
  ["about", "Informations système", "a propos pc version processeur memoire"],
].map(([page, name, keywords]) => ({ page, name, keywords }));
